server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:mysql://192.168.83.128:3306/dbCloud?useUnicode=true&characterEncoding-utf-8&useSLL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver

mybatis:
  mapper-locations: classpath:mybatis/mappers/*.xml
  type-aliases-package: com.xiao.springCloud.beans
#  config-location: classpath:mybatis/myBatisConfig.xml

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true
